GET http://localhost:3002/api/blogs HTTP/1.1

###
DELETE http://localhost:3002/api/blogs/66d8211f761f4b5c233d6690  HTTP/1.1



###
POST http://localhost:3002/api/blogs HTTP/1.1
Content-Type: application/json

{
    "title": "test1",
    "author": "john doe",
    "url": "localhost.com",
    "likes":0
}


###
PUT  http://localhost:3002/api/blogs/66d47a65a03d8a18eaf10a1e HTTP/1.1
Content-Type: application/json

{
    "title": "hello, world",
    "author": "john doe",
    "url": "none",
    "likes":2
}
