GET http://localhost:3002/api/blogs HTTP/1.1

###
DELETE http://localhost:3002/api/blogs/  HTTP/1.1



###
POST http://localhost:3002/api/blogs HTTP/1.1
Content-Type: application/json

{
    "title": "hello, world",
    "author": "john doe",
    "url": "none",
    "likes":0
}


###
PUT  http://localhost:3002/api/blogs/66d47a65a03d8a18eaf10a1d HTTP/1.1
Content-Type: application/json

{
    "title": "hello, world",
    "author": "john doe",
    "url": "none",
    "likes":324
}
